### ISSUE TITLE
add a "local" option to the server combo box

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclist2#100]
I know this was discussed previously, but I think this is related to #99

**Comment by FlanFlanagan** [comment]
Looks like it's already there.

![image](https://cloud.githubusercontent.com/assets/737899/8020970/580a3cde-0c53-11e5-9320-4d268f94378b.png)

**Comment by gidden** [comment]
that's new

**Comment by yarden-livnat** [comment]
We talked about it on Wednesday so I went ahead and implemented it. It should make switching between servers, adding and removing servers much simpler. The list of servers persists between runs. I also remove the 'Run" menu from the top level menubar.

To add a sever: select the '-- add new --' option and type the new url
To remove: select it and clear the entry
