### ISSUE TITLE
month is not 1-indexed

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclist2#112]
a value of January puts a "0" in the input file, which is not valid (must be `[1, 12]`) 

@FlanFlanagan, do you know off the top of your head how to do this? It should be easy (i just don't know where) -- just print i + 1.

**Comment by FlanFlanagan** [comment]
I will update the outdated

**Comment by FlanFlanagan** [comment]
er output

**Comment by FlanFlanagan** [comment]
This should be fixed with #101 . I'm going to close for now.
