### ISSUE TITLE
Null commodities

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclist2#117]
If a user opens the commodity combobox before any commodities are defined the commodity is set as "" or (null).

If a user does this on an incommod of one prototype and the outcommod of another prototype, they become connected with a nameless commodity arrow.

**Comment by FlanFlanagan** [comment]
I'm sorry, this ones actually kind of funny...I'll take a look.

**Comment by FlanFlanagan** [comment]
I have a fix for this but it causes another issue. If there is a commodity with an empty name, as in the user has not put in a name for that commodity it will not show a connection but an empty value will show in the commod dropdown.

**Comment by FlanFlanagan** [comment]
I can that fix.

**Comment by FlanFlanagan** [comment]
fixed in #118
