### ISSUE TITLE
Saving files that were loaded doesn't work

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclist2#119]
It appears that data for the recursive data containers is not being written back out properly.  It does appear correctly in the configure forms, so I can confirm that it's being read in correctly, but it is somehow not in the right data structures to be written back out correctly.

For example, the reactor's outcommodity.  I even tried to change it in the UI to see if that would reset it, but it didn't help.

On the minor side - the niche is also not restored.

**Comment by FlanFlanagan** [comment]
I'm not sure what's happening. I'm not seeing this issue. 

Are you saving, and then loading without closing Cyclist? Because if that's the case then I can probably do something to fix it. It should probably clear the current scenario if you try to load. 

I fixed the niche thing with the most recent push.

**Comment by gidden** [comment]
Hi Robert,

I saw this issue as well. The process was:

open cyclist -> make & save scenario -> close cyclist -> open cyclist ->
load scenario -> try to save scenario.

The last step will fail.

Matt

On Mon, Jun 8, 2015 at 6:22 PM, FlanFlanagan <notifications@github.com>
wrote:

> I'm not sure what's happening. I'm not seeing this issue.
>
> Are you saving, and then loading without closing Cyclist? Because if
> that's the case then I can probably do something to fix it. It should
> probably clear the current scenario if you try to load.
>
> I fixed the niche thing with the most recent push.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/119#issuecomment-110170307>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by FlanFlanagan** [comment]
I believe you guys, I just haven't seen this issue yet so I'm not sure how to troubleshoot it. In the long term we definitely need to fix it if we can figure out what is causing the issue.

**Comment by gonuke** [comment]
I was able to save after fixing an issue with converting startmonth back into an integer.  But if you look at the file that is saved, it is missing stuff.

For me, the process was :
- save file as 1
- quit cyclist
- start cyclist
- load file
- save file as 2
- compare 1 vs 2

**Comment by FlanFlanagan** [comment]
I'm seeing the issue now. But the issue isn't in the serialization because when I load file 2 I see the fields that are missing populated with the proper values. What's happening here is an issue with the writing out. 

Also if I read in file 2 and save as file 3, 2 = 3.

**Comment by FlanFlanagan** [comment]
Do you guys want me to fix this?

**Comment by FlanFlanagan** [comment]
The issue appears to be happening in orMore objects. I'll try and fix it.

**Comment by FlanFlanagan** [comment]
This should now be fixed in my most recent PR.

**Comment by gonuke** [comment]
This fixed many things, but recipes are still behaving the same way:
* the loaded information shows up correctly in the foms but doesn't get written back out correctly.

**Comment by gonuke** [comment]
Resolved with #130
