### ISSUE TITLE
Java executable not building

### ISSUE THREAD

**Issue by eriewski** [cyclus/cyclist2#157]
Hello, I am currently working as an undergraduate research student for @katyhuff 
Prof. Huff recommended I ping @flanflanagan in this issue for assistance

After cloning the cyclus/cyclist2 directory, the executable fails to build when I run 'ant'. I get the following error when trying to build the Java executable. 

 [javac] /home/eric/cyclist2/deploy/build/src/edu/utexas/cycic/FormBuilderFunctions.java:650: error: cannot find symbol
    [javac]             Dialog dg = PopUpFunctions.buildPopUp();
    [javac]                         ^
    [javac]   symbol:   variable PopUpFunctions
    [javac]   location: class FormBuilderFunctions
    [javac] Note: /home/eric/cyclist2/deploy/build/src/edu/utexas/cycic/TimelineDisplay.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

I am pretty confident I have Java 8 up to data on my virtual machine. Apparently a deprecated API is in the code that builds the Java executable. I was wondering if there was any problem with the code or there is something wrong on my end.

Eric

**Comment by yarden-livnat** [comment]
Eric,

Robert might have insight for this particular problem. As far as Java 8, 
I assume you mean you have the latest JDK on your machine. Note that 
regular Java 8 updates typically involved only updating the JRE on your 
machine.

Yarden

eriewski wrote:

**Comment by FlanFlanagan** [comment]
I'll look into this when I get some time this evening.

**Comment by FlanFlanagan** [comment]
@eriewski 

Two things:
Which branch are you on? 

and can you run the following command in a terminal and paste the result here. 
update-alternatives --config java

Thanks!

**Comment by eriewski** [comment]
Sorry for the late reply.
I am on the top branch of cyclist2. /cyclist2$
When running the following command, I get the following: "There is only one alternative in link group java (providing /usr/bin/java): /usr/lib/jvm/java-8-oracle/jre/bin/java
Nothing to configure."

**Comment by FlanFlanagan** [comment]
Could you do a 
`git checkout develop`
in your cyclist2 directory to switch to the develop branch. It's possible you're on the 'master' branch.

**Comment by eriewski** [comment]
@flanflanagan

Thank you very much. This solved my problem.
