### ISSUE TITLE
Commodity changes with 'orMore' removals

### ISSUE THREAD

**Issue by FlanFlanagan** [cyclus/cyclist2#22]
Need logic to remove commodities (in and out) from commodity arrays on prototypes.

FormBuilder.java line 135

Will be difficult. Requires knowledge of my internal structures.

**Comment by gidden** [comment]
I think this is the issue tackled in #104. Can you provide a short description of what the problem is here so I know what to test? Thanks!

**Comment by FlanFlanagan** [comment]
PR #104

**Comment by FlanFlanagan** [comment]
Issue #116 holds this now
