### ISSUE TITLE
Auto generate nullRegion/nullInst

### ISSUE THREAD

**Issue by FlanFlanagan** [cyclus/cyclist2#29]
Difficult ish. Should be done via popup prompt.

**Comment by gonuke** [comment]
I think we should also put 1 of every prototype in the initialfacility list for the NullInst, when doing this.

**Comment by gidden** [comment]
Agreed.

On Wed, Jun 3, 2015 at 9:28 AM, Paul Wilson <notifications@github.com>
wrote:

> I think we should also put 1 of every prototype in the initialfacility
> list for the NullInst, when doing this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/29#issuecomment-108454302>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by FlanFlanagan** [comment]
Oh sorry, yeah. I assumed that was going to be the case. Doesn't really work otherwise.

**Comment by gidden** [comment]
assigned to @FlanFlanagan for more clarification

**Comment by FlanFlanagan** [comment]
You still on this Matt or want me to take it?

**Comment by gidden** [comment]
Can you take it? It will require knowledge of the *Array datatypes.

On Fri, Jun 5, 2015 at 2:47 PM, FlanFlanagan <notifications@github.com>
wrote:

> You still on this Matt or want me to take it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/29#issuecomment-109419179>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by FlanFlanagan** [comment]
Will do!

**Comment by gonuke** [comment]
Let me know if you want me to work on this on the plane, along with #30

**Comment by gonuke** [comment]
(boarding within 15 minutes, or so)

**Comment by FlanFlanagan** [comment]
PR #114  addresses this.
