### ISSUE TITLE
Shift text to bottom of circles. 

### ISSUE THREAD

**Issue by FlanFlanagan** [cyclus/cyclist2#31]
CycicCircles.Java

circle.text needs to be moved to below circle. 

Note I use center - radius*.6 right now to set it to show up in the upper left corner of the circle. Should only need to change the y value to take this above or below.

**Comment by gonuke** [comment]
I've got this figured out, in principle, but the changes I make don't seem to have any effect...  I was able to make the archetypes have a different label location, but the same change for the prototypes failed to make a difference.

I'll try some more tomorrow

**Comment by gonuke** [comment]
Figured it out... text placement was happening in many places

**Comment by gonuke** [comment]
Fixed by #42.  Maybe some more tweaking, but it is all centralized now.
