### ISSUE TITLE
Consider moving "Node Skins" and "Save Diagram"

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclist2#43]
The Node Skins and Save FC Diagram widgets appear to be part of the "Add prototype" form.

Some other possible locations are:
* context menu (right click) of background pane
* top-level menu
* bottom of pane

**Comment by gonuke** [comment]
Perhaps also the "Local" & "Remote" switch

**Comment by FlanFlanagan** [comment]
I think that bottom or in the context pane make the most sense. At least for in the main view. That doesn't mean we can't put it on the top level

**Comment by FlanFlanagan** [comment]
Two of these are done. 

Paul how do you feel about this change to the execution environment toggle?

![image](https://cloud.githubusercontent.com/assets/737899/7960191/26c5f0c8-09c4-11e5-8730-6ad99a322325.png)

**Comment by gonuke** [comment]
That change looks fine to me.  If I was greedy, I'd wonder about using either radio buttons or a combo box, but moving the buttons there is fine with me.

**Comment by FlanFlanagan** [comment]
I think a comboBox or radio buttons is fine. I'll put both in an post some pictures to get opinions.

**Comment by FlanFlanagan** [comment]
New demo, what's everyone's opinion.

![image](https://cloud.githubusercontent.com/assets/737899/7965622/553cc2ae-09e4-11e5-8d4a-482320f0f6bd.png)

**Comment by gidden** [comment]
I'm +1 on the radio button

On Wed, Jun 3, 2015 at 11:33 AM, FlanFlanagan <notifications@github.com>
wrote:

> New demo, what's everyone's opinion.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/737899/7965622/553cc2ae-09e4-11e5-8d4a-482320f0f6bd.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/43#issuecomment-108513843>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gonuke** [comment]
Closed by #60

**Comment by yarden-livnat** [comment]
Robert, 
   Do you mean the changes I made?
