### ISSUE TITLE
There are no Institutions or Region Archetypes if their corrals are opened before the Main Window

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclist2#49]

**Comment by FlanFlanagan** [comment]
I have code for this. I will get it back in.I had turned it off for testing purposes.

**Comment by gonuke** [comment]
@FlanFlanagan Do you want me to take a look at this?  I would do it by just calling archetype discovery when these are opened.

**Comment by FlanFlanagan** [comment]
@gonuke Sure. That should work as long as we aren't adding multiples to the simulation.

**Comment by gidden** [comment]
We are assigning issues in the dev call and it looks like you volunteered, @gonuke =)

**Comment by gidden** [comment]
@FlanFlanagan has this been fixed?

**Comment by gonuke** [comment]
fixed by #77
