### ISSUE TITLE
Adding/Removing Institutions from Regions

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclist2#52]
I created a null region and tried to add institutions:
* with no institutions defined, clicking the add button added "null"
* there is no button to delete an institution
* right-clicking on an institution deletes it (I discovered this accidentally and its non-intuitive)

**Comment by gonuke** [comment]
Also... when I close the region form and re-open, the institution is gone.  When I re-add it, I get 2 copies. then I close & open again and its gone.... etc.

**Comment by FlanFlanagan** [comment]
I have a fix for issues 1, and 3. 

Issue 2 is a less obvious fix, i.e. where should the remove button exist?

**Comment by gonuke** [comment]
Maybe convert "right-click = delete" to "right-click = menu with choice to delete"  This is kind of like a file-browser...

**Comment by FlanFlanagan** [comment]
That should be possible. It will depend on how the objects in a listview can be interacted with.

**Comment by gonuke** [comment]
Closed by merging #64
