### ISSUE TITLE
Ability to read an XML input file

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclist2#61]
@FlanFlanagan is this possible before the tutorial?

**Comment by FlanFlanagan** [comment]
A Cycic generated input file, or a non Cycic generated input file?

Also, I think there was a Cyclus input file tag that was set aside for this but I honestly don't remember it. Maybe Matt knows.

**Comment by gidden** [comment]
There is a `ui` tag in which you can put any text. The idea here being that
you can generate an input file in cycic, dump cycic-specific information
(e.g., a json object) in the ui tag, and read that back in to return to the
original state.

This seems like a lot of work, but perhaps it is not..

On Tue, Jun 2, 2015 at 7:52 AM, FlanFlanagan <notifications@github.com>
wrote:

> A Cycic generated input file, or a non Cycic generated input file?
>
> Also, I think there was a Cyclus input file tag that was set aside for
> this but I honestly don't remember it. Maybe Matt knows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/61#issuecomment-107943492>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by FlanFlanagan** [comment]
I think I can get CycIC generated inputs done. Loading a non CycIC generated input is going to be pretty difficult just because placing things will  be tough.

**Comment by FlanFlanagan** [comment]
Note, I have work to do til Wednesday then I can switch over to this.

**Comment by gidden** [comment]
agreed

On Tue, Jun 2, 2015 at 11:29 AM, FlanFlanagan <notifications@github.com>
wrote:

> I think I can get CycIC generated inputs done. Loading a non CycIC
> generated input is going to be pretty difficult just because placing things
> will be tough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/61#issuecomment-108006857>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gonuke** [comment]
I think laying out nodes for an arbitrary input file is a bonus.  I'd be happy, at this stage, if it was laid out in any way and the user could rearrange it.

**Comment by FlanFlanagan** [comment]
Mkay. 

One more issue that I see coming up. Loading an input file not generated in CycIC without access to Cyclus or a specific archetype in the input file. Without some access to a cyclus -m type file I don't think this is feasible (with a CycIC generated file I can simple put that information into the <UI> tag).

**Comment by gonuke** [comment]
This is a longer term issue, but one way to get a start on this would be to:
* identify that you were encountering an unknown archetype
* try running cyclus to get metadata for it, and if not fruitful
* notify the user that they will not be able to edit anything about that archetype
* store the full <config> block from the XML as a fixed string
* create a form that only allows the user to change Facility class elements: name, commodities
* when re-writing the file, just dump the <config> block as read.

One alternative would be to let users edit the <config> block in a textarea....

**Comment by gidden** [comment]
I agree that this is a longer term issue. At *most* we would want
capability to re-read in files Cycic has already saved. I'm not sure we
even have time for that before the tutorial, but I'm not the one
implementing it =).

On Wed, Jun 3, 2015 at 9:21 AM, Paul Wilson <notifications@github.com>
wrote:

> This is a longer term issue, but one way to get a start on this would be
> to:
>
>    - identify that you were encountering an unknown archetype
>    - try running cyclus to get metadata for it, and if not fruitful
>    - notify the user that they will not be able to edit anything about
>    that archetype
>    - store the full block from the XML as a fixed string
>    - create a form that only allows the user to change Facility class
>    elements: name, commodities
>    - when re-writing the file, just dump the block as read.
>
> One alternative would be to let users edit the block in a textarea....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/61#issuecomment-108449405>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by FlanFlanagan** [comment]
First cut at this in PR #113

**Comment by FlanFlanagan** [comment]
finalized in #118

**Comment by gonuke** [comment]
#130 fixed a final bug - considered resolved for now
