### ISSUE TITLE
using the "add prototype" bar at the top of the main view does not apply the same skin

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclist2#68]
e.g.

![image](https://cloud.githubusercontent.com/assets/1392657/7947057/3dc81a64-0940-11e5-950e-6629e3f497a0.png)

**Comment by FlanFlanagan** [comment]
Should be an easy fix, just a quick copy paste of the dnd code to add a
circle to the button code to add a circle.

**Comment by gidden** [comment]
I'm not sure I follow that..

**Comment by FlanFlanagan** [comment]
I got it


On Tue, Jun 2, 2015 at 4:00 PM, Matthew Gidden <notifications@github.com>
wrote:

> I'm not sure I follow that..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/68#issuecomment-108097546>.
>



-- 
Robert Flanagan
Graduate Research Assistant
Nuclear and Radiation Engineering Program
Department of Mechanical Engineering
The University of Texas at Austin

**Comment by FlanFlanagan** [comment]
I fixed this with #70
