### ISSUE TITLE
syncronize cycic/list with cloudlus and 1.3.1

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclist2#76]
assigning to @FlanFlanagan, but it will be a bit of a team effort

**Comment by FlanFlanagan** [comment]
What needs to be done here? 

Discover archetypes should work.

**Comment by gidden** [comment]
True.

On Fri, Jun 5, 2015 at 2:46 PM, FlanFlanagan <notifications@github.com>
wrote:

> What needs to be done here?
>
> Discover archetypes should work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/76#issuecomment-109418744>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192
