### ISSUE TITLE
the data exploration tab automatically opens cycic

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclist2#82]
I assume this is not to be expected?

**Comment by gidden** [comment]
also, shouldn't that probably be happening in the scenario builder tab? perhaps just flip their startup functions..

**Comment by gidden** [comment]
assigning to yarden for now. I am happy to tackle if given some direction.

**Comment by FlanFlanagan** [comment]
I'm not seeing this issue and I just pulled. Does this happen all the time for you?

**Comment by gidden** [comment]
Yes. I have a possible fix in a PR.

On Fri, Jun 5, 2015 at 11:23 AM, FlanFlanagan <notifications@github.com>
wrote:

> I'm not seeing this issue and I just pulled. Does this happen all the time
> for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/82#issuecomment-109351403>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by yarden-livnat** [comment]
Nice catch :-)

I assume this happened only the first time you run Cyclist after the new perspective were put in. Is that right?

**Comment by gidden** [comment]
As far as I can tell, yes. Anytime I build and open, the cycic main view
pops up in the "data exploration" pane.

On Fri, Jun 5, 2015 at 11:32 AM, Yarden <notifications@github.com> wrote:

> Nice catch :-)
>
> I assume this happened only the first time you run Cyclist after the new
> perspective were put in. Is that right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/82#issuecomment-109355303>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by yarden-livnat** [comment]
Did you delete the view and save the workspace?

**Comment by gidden** [comment]
I did not save any workspaces.

On Fri, Jun 5, 2015 at 12:12 PM, Yarden <notifications@github.com> wrote:

> Did you delete the view and save the workspace?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/82#issuecomment-109367105>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by yarden-livnat** [comment]
Oh. That’s why it kept coming back. I assume the problem disappeared after you fixed that bug.

**Comment by gidden** [comment]
Yes, I have a PR in at https://github.com/cyclus/cyclist2/pull/88 if you
want to review it.

On Fri, Jun 5, 2015 at 12:59 PM, Yarden <notifications@github.com> wrote:

> Oh. That’s why it kept coming back. I assume the problem disappeared after
> you fixed that bug.
>
> > On Jun 5, 2015, at 11:58 AM, Matthew Gidden <notifications@github.com>
> wrote:
> >
> > I did not save any workspaces.
> >
> > On Fri, Jun 5, 2015 at 12:12 PM, Yarden <notifications@github.com>
> wrote:
> >
> > > Did you delete the view and save the workspace?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cyclus/cyclist2/issues/82#issuecomment-109367105>.
> > >
> >
> >
> >
> > --
> > Matthew Gidden, Ph.D.
> > Postdoctoral Associate, Nuclear Engineering
> > The University of Wisconsin -- Madison
> > Ph. 225.892.3192
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/cyclus/cyclist2/issues/82#issuecomment-109380979>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/82#issuecomment-109381239>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
done
