### ISSUE TITLE
remove cycaless facilities from defaults

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclist2#83]
the cycaless facilities were a one-time bandaid, they are not needed any more. Is this a simple `cyclus -m` dump @FlanFlanagan? also, can you provide instructions for how to update that in general?

**Comment by gidden** [comment]
assigning to @FlanFlanagan for now. I am happy to tackle if given some direction.

**Comment by FlanFlanagan** [comment]
cyclus -m >default-metadata.json

in the cyclist folder of cyclist2 will update the metadata.

**Comment by gidden** [comment]
done
