### ISSUE TITLE
the remote server being used to run remote jobs is not obvious

### ISSUE THREAD

**Issue by gidden** [cyclus/cyclist2#90]
It would be nice to have a check mark or something. Perhaps write out the name being used next to the remote button?

**Comment by gidden** [comment]
I think putting the name next to the remote button is the easiest way forward.

**Comment by FlanFlanagan** [comment]
Cycic.java 

Line 711-749. 

Lines 718-738 are local

**Comment by yarden-livnat** [comment]
New server selection (and add/remove) in Cycic.
Removed the "Run" menubar
